SectionVerb {
    Value {
        TQ "HiFi"
    }
    EnableSequence [
        cset "name='codec_out0 Gain 0 Volume' 72%"
        cset "name='IF2 ADC Mux' DAC_REF"
        cset "name='IF3 ADC Mux' IF_ADC1"
    ]
}

SectionDevice."Speaker" {
    Comment "Built-in stereo speakers (dual TFA9890)"
    Value {
        PlaybackPriority 100
        PlaybackPCM "hw:${CardId},0"
        PlaybackMixerElem "DAC1"
        PlaybackChannels 2
    }
    EnableSequence [
        cset "name='Headphone Switch' off"
        cset "name='Ext Spk Switch' on"
        cset "name='Amp Input' Left"
        cset "name='Amp Input1' Right"
        cset "name='DAC1 Playback Switch' on"
    ]
    DisableSequence [
        cset "name='DAC1 Playback Switch' off"
        cset "name='Ext Spk Switch' off"
    ]
}

SectionDevice."Headphones" {
    Comment "3.5mm headphones"
    Value {
        PlaybackPriority 200
        PlaybackPCM "hw:${CardId},0"
        PlaybackMixerElem "Headphone"
        PlaybackChannels 2
    }
    EnableSequence [
        cset "name='Ext Spk Switch' off"
        cset "name='Headphone Switch' on"
    ]
    DisableSequence [
        cset "name='Headphone Switch' off"
    ]
}

SectionDevice."IntMic" {
    Comment "Built-in microphone"
    Value {
        CapturePriority 100
        CapturePCM "hw:${CardId},0"
        CaptureMixerElem "IN"
        CaptureChannels 2
    }
    EnableSequence [
        cset "name='Headset Mic Switch' off"
        cset "name='Int Mic Switch' on"
        cset "name='RECMIX1L BST3 Switch' on"
        cset "name='RECMIX1R BST4 Switch' on"
        cset "name='Stereo1 ADC Source' ADC1"
        cset "name='Stereo1 ADC1 Source' ADC"
        cset "name='Stereo1 ADC MIXL ADC1 Switch' on"
        cset "name='Stereo1 ADC MIXR ADC1 Switch' on"
        cset "name='STO1 ADC Capture Switch' on"
        cset "name='IN Capture Volume' 23,23"
        cset "name='STO1 ADC Capture Volume' 70,70"
    ]
    DisableSequence [
        cset "name='Int Mic Switch' off"
        cset "name='RECMIX1L BST3 Switch' off"
        cset "name='RECMIX1R BST4 Switch' off"
        cset "name='STO1 ADC Capture Switch' off"
    ]
}

SectionDevice."HeadsetMic" {
    Comment "Headset microphone"
    Value {
        CapturePriority 200
        CapturePCM "hw:${CardId},0"
        CaptureMixerElem "IN"
        CaptureChannels 2
    }
    EnableSequence [
        cset "name='Int Mic Switch' off"
        cset "name='Headset Mic Switch' on"
        cset "name='RECMIX1L INL Switch' on"
        cset "name='RECMIX1R INR Switch' on"
        cset "name='Stereo1 ADC Source' ADC1"
        cset "name='Stereo1 ADC1 Source' ADC"
        cset "name='Stereo1 ADC MIXL ADC1 Switch' on"
        cset "name='Stereo1 ADC MIXR ADC1 Switch' on"
        cset "name='STO1 ADC Capture Switch' on"
        cset "name='IN Capture Volume' 80,80"
        cset "name='STO1 ADC Capture Volume' 70,70"
    ]
    DisableSequence [
        cset "name='Headset Mic Switch' off"
        cset "name='RECMIX1L INL Switch' off"
        cset "name='RECMIX1R INR Switch' off"
        cset "name='STO1 ADC Capture Switch' off"
        cset "name='Int Mic Switch' on"
    ]
}
